package pt.isec.pd.tp.Client.logica;

public enum ClientState {
    LOGGED_IN,
    LOGIN,
    REGISTER,
    DOCENTE_HOME,
    ESTUDANTE_HOME,
    CRIAR_PERGUNTA,
    CONSULTAR_PERGUNTA,
    LISTAR_PERGUNTAS,
    LISTA_PERGUNTAS_RESPONDIDAS,
    RESPONDER_PERGUNTA,
    DETALHES_PERGUNTA,
    DETALHES_PERGUNTA_ESTUDANTE,
    LISTAR_CLIENTES,
    EDITAR_PERGUNTA,
    EDITAR_PERFIL_DOCENTE,
    EDITAR_PERFIL_ESTUDANTE, AGUARDAR_SERVIDOR
}
